AllCops:
  Exclude:
    - tmp/vulnerabilities/spec/*

Metrics/BlockLength:
  Exclude:
    - spec/lib/generic_app_spec.rb

Metrics/LineLength:
  Exclude:
    - generic_app.gemspec
    - lib/generic_app.rb
    - spec/lib/generic_app_spec.rb

Metrics/MethodLength:
  Exclude:
    - lib/generic_app.rb

Style/RedundantSelf:
  Exclude:
    - lib/generic_app.rb

Style/VariableNumber:
  Enabled: false
