Metrics/LineLength:
  Exclude:
    - generic_app.gemspec
    - lib/generic_app.rb
    - spec/lib/1_sqlite_spec.rb

Metrics/MethodLength:
  Exclude:
    - lib/generic_app.rb

Style/RedundantSelf:
  Exclude:
    - lib/generic_app.rb
